package nov2019

const (
	TYPE_ADDRESS_WHITELIST_IF_OTHER = 9

	TYPE_ADDRESS_BLOCK_TO_INSTANT     = 10
	TYPE_ADDRESS_BLOCK_FROM_INSTANT   = 20
	TYPE_ADDRESS_BLOCK_FROMTO_INSTANT = 30

	TYPE_ADDRESS_BLOCK_TO_SINCE_HEIGHT     = 100
	TYPE_ADDRESS_BLOCK_FROM_SINCE_HEIGHT   = 200
	TYPE_ADDRESS_BLOCK_FROMTO_SINCE_HEIGHT = 200

	TYPE_ADDRESS_BLOCK_TO_BEFORE_HEIGHT     = 1000
	TYPE_ADDRESS_BLOCK_FROM_BEFORE_HEIGHT   = 2000
	TYPE_ADDRESS_BLOCK_FROMTO_BEFORE_HEIGHT = 2000

	LOG_PREFIX = "[NOV2019] 🦊 "
)

type FilterRecord struct {
	Type   int
	Param1 int
	Param2 string
	Param3 map[string]FilterRecord
}

type UpgradeNov2019Migrator struct {
	currentHeightDbg int
	flag1810oneshot  bool
}
