#!/bin/bash -vuex
reset;

export NOV2019_FORCE_ADDR=1;
export NOV2019_DISABLE_NODELIST=1;
export NOV2019_RETESTNET=1;
export NOV2019_AT_HEIGHT_NOT_BEFORE=100;
export NOV2019_AT_HEIGHT_NOT_AFTER=1000;
export NOV2019_DISABLE_NODELIST=1;

id=$(hostname | grep -oP "^\w*");
dd=~/.yocoin-test-data
yoc=/opt/yocoin-2.0.1119-debug
yh="--yochash.dagdir $dd/yhd --yochash.cachedir $dd/yhc";
ip=$(getent hosts $(hostname) | cut -d' ' -f1);

#cfg=test.cfg;
port=19303;
rport=18547;

offtopic=0x384c419e234d173c761d9752f6c1b6c48fe8c942;
super=fde53fa41cdfee341ff701a6402ca59d0c468f3d;

[ ! -d $dd ] && $yoc --datadir $dd $yh init genesis.dev.json && (cp UTC-* /opt/UTC-* $dd/keystore/ || true );

function cfg {
	yoc --datadir $dd $yh dumpconfig | sed '1,2d' > $cfg;
	sed -i "s/ListenAddr = \"\d*.*/ListenAddr = \"$ip:$port\"/" $cfg;
}
#cfg

cp UTC-* $dd/keystore/ || true;
$yoc --datadir $dd $yh \
	--viplog --debug --vmdebug \
        --identity $id --extradata Yocoin2_TestNov19_UpgradeStart_$id \
	--port $port \
        --rpccorsdomain '*' --rpc  --rpcport $rport --rpcaddr $ip --rpcvhosts '*' --rpcapi yoc,web3,net,personal,eth,miner \
        --syncmode full \
	--nat none \
	--port $port \
	--mine \
	--yocbase $offtopic \
        console $*;

#	--config $cfg \
#	--nat extip:$ip \
